from fastapi import APIRouter, Request
from app.core.data_loader import DataLoader
from app.core.planner_engine import plan_multiple_sprints

router = APIRouter()

@router.get("/plan/{project_id}")
async def plan_sprint_for_project(project_id: str, request: Request):
    print(f"🚀 Sprint planning initiated for Project: {project_id}")

    try:
        # --- STEP 1: Forward authorization headers if provided ---
        incoming = {}
        if "authorization" in request.headers:
            incoming["Authorization"] = request.headers.get("authorization")
        if "cookie" in request.headers:
            incoming["Cookie"] = request.headers.get("cookie")

        # --- STEP 2: Fetch full project data ---
        loader = DataLoader(project_id, incoming_headers=incoming)
        data = await loader.get_project_data()
        members, tasks = data["members"], data["tasks"]

        print(f"📊 Loaded {len(members)} members and {len(tasks)} tasks.")

        # --- STEP 3: Generate sprints (AI summaries handled inside planner) ---
        sprints = await plan_multiple_sprints(project_id, members, tasks)

        if not sprints:
            print("⚠️ No sprints generated by planner.")
            return {"success": False, "message": "No sprints generated."}

        print(f"🏁 Successfully generated {len(sprints)} sprints with AI summaries and goals.")
        return {"success": True, "projectId": project_id, "sprints": sprints}

    except Exception as e:
        print(f"❌ Route error: {e}")
        return {"success": False, "error": str(e)}
